In [1]:
import torch

In [2]:
z = torch.Tensor(4,5)
print(z)
print(z.dtype)

tensor([[2.7108e-35, 0.0000e+00, 7.0065e-44, 6.7262e-44, 6.3058e-44],
        [6.7262e-44, 7.9874e-44, 6.3058e-44, 6.7262e-44, 7.7071e-44],
        [1.1771e-43, 6.8664e-44, 7.5670e-44, 8.1275e-44, 7.4269e-44],
        [7.1466e-44, 8.1275e-44, 7.1466e-44, 7.1466e-44, 6.4460e-44]])
torch.float32


In [3]:
a = torch.FloatTensor(4,5)
b = torch.FloatTensor([2,3,4,5])
print(a)
print(a.dtype)
print(b)
print(b.dtype)

tensor([[2.7108e-35, 0.0000e+00, 7.0065e-44, 6.7262e-44, 6.3058e-44],
        [6.7262e-44, 7.9874e-44, 6.3058e-44, 6.7262e-44, 7.7071e-44],
        [1.1771e-43, 6.8664e-44, 7.5670e-44, 8.1275e-44, 7.4269e-44],
        [7.1466e-44, 8.1275e-44, 7.1466e-44, 7.1466e-44, 6.4460e-44]])
torch.float32
tensor([2., 3., 4., 5.])
torch.float32


In [4]:
a = torch.IntTensor(4,5)
b = torch.IntTensor([2,3,4,5])
print(a)
print(a.dtype)
print(b)
print(b.dtype)

tensor([[101720576,         0,        50,        48,        45],
        [       48,        57,        45,        48,        55],
        [       84,        49,        54,        58,        53],
        [       51,        58,        51,        51,        46]],
       dtype=torch.int32)
torch.int32
tensor([2, 3, 4, 5], dtype=torch.int32)
torch.int32


In [5]:
y = a + z
print(y)
print(y.dtype)

tensor([[1.0172e+08, 0.0000e+00, 5.0000e+01, 4.8000e+01, 4.5000e+01],
        [4.8000e+01, 5.7000e+01, 4.5000e+01, 4.8000e+01, 5.5000e+01],
        [8.4000e+01, 4.9000e+01, 5.4000e+01, 5.8000e+01, 5.3000e+01],
        [5.1000e+01, 5.8000e+01, 5.1000e+01, 5.1000e+01, 4.6000e+01]])
torch.float32


In [6]:
print(torch.add(a,z))

tensor([[1.0172e+08, 0.0000e+00, 5.0000e+01, 4.8000e+01, 4.5000e+01],
        [4.8000e+01, 5.7000e+01, 4.5000e+01, 4.8000e+01, 5.5000e+01],
        [8.4000e+01, 4.9000e+01, 5.4000e+01, 5.8000e+01, 5.3000e+01],
        [5.1000e+01, 5.8000e+01, 5.1000e+01, 5.1000e+01, 4.6000e+01]])


In [7]:
b = a.numpy()
print(b)

[[101720576         0        50        48        45]
 [       48        57        45        48        55]
 [       84        49        54        58        53]
 [       51        58        51        51        46]]


In [8]:
import numpy as np

In [9]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [10]:
c = b.float()
print(c)
print(c.dtype)

tensor([1., 1., 1., 1., 1.])
torch.float32


In [11]:
print(c.int())

tensor([1, 1, 1, 1, 1], dtype=torch.int32)


In [12]:
x = torch.zeros(2,1,2,1,2) # 有時會想多加一個沒有厚度的維度
print(x)
x.size()

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])


torch.Size([2, 1, 2, 1, 2])

Tensor(2,1,3) 
-> 由d2(3)開始看 [1,2,3] 
-> [[1,2,3]] 
-> [[[1,2,3]],[[5,6,7]]]

In [13]:
y = x.squeeze() # 再透過squeeze消除
print(y)
y.size()

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


torch.Size([2, 2, 2])

In [14]:
z = x.squeeze(0) # 對維度0
z.size()

torch.Size([2, 1, 2, 1, 2])

In [15]:
z = x.squeeze(1)
z.size()

torch.Size([2, 2, 1, 2])

In [16]:
torch.abs(torch.FloatTensor([-1,-2,-3]))

tensor([1., 2., 3.])

In [17]:
a = torch.randn(4) # 有正負
a

tensor([ 0.0101, -0.1027,  0.8979, -0.8885])

In [18]:
b = torch.add(a,-20)
b

tensor([-19.9899, -20.1027, -19.1021, -20.8885])

In [19]:
c = torch.mul(a,b) # 對應位置相乘
c

tensor([ -0.2022,   2.0638, -17.1526,  18.5597])

In [20]:
x = torch.rand(2,3)
y = torch.rand(3,2)
print(x)
print(y)

tensor([[0.4821, 0.4846, 0.5198],
        [0.3661, 0.5540, 0.5049]])
tensor([[0.6897, 0.1840],
        [0.4684, 0.0906],
        [0.2206, 0.3702]])


In [21]:
z = torch.matmul(x,y) # 2x3 * 3x2 = 2x2
z

tensor([[0.6742, 0.3251],
        [0.6234, 0.3045]])

In [22]:
z = torch.matmul(y,x)
z

tensor([[0.3999, 0.4362, 0.4514],
        [0.2590, 0.2772, 0.2893],
        [0.2419, 0.3120, 0.3016]])

In [23]:
torch.mean(z) # 平均

tensor(0.3298)

In [24]:
torch.mean(z,0) # 對0維度((v1+v2+v3)/3)平均

tensor([0.3003, 0.3418, 0.3474])

In [25]:
torch.mean(z,1)

tensor([0.4292, 0.2752, 0.2851])

In [26]:
x = torch.Tensor([[1,2],[3,4]])
y = torch.Tensor([[1,1],[4,4]])
torch.eq(x,y)

tensor([[ True, False],
        [False,  True]])

In [27]:
torch.ge(x,y)

tensor([[ True,  True],
        [False,  True]])

In [28]:
torch.gt(x,y)

tensor([[False,  True],
        [False, False]])

In [29]:
torch.le(x,y)

tensor([[ True, False],
        [ True,  True]])

In [30]:
torch.lt(x,y)

tensor([[False, False],
        [ True, False]])

In [31]:
torch.equal(x,y)

False